server:
  port: 8080
#  error:
#    whitelabel:
#      enabled: false
#  servlet:
#    context-path: /demo

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://127.0.0.1:3306/demo?characterEncoding=UTF-8&serverTimeZone=UTC
    username: root
    password: 1111

  servlet:
    multipart:
      max-file-size: 10GB # 파일 최대 크기 (예: 10GB)
      max-request-size: 10GB # 요청 최대 크기 (예: 10GB)

#  jackson:
#    property-naming-strategy: SNAKE_CASE # Java 객체 <-> JSON 변환 시 속성 네이밍 전략 설정

  mybatis:
    mapper-locations: classpath:/mapper/*/*.xml
#    configuration:
#      map-underscore-to-camel-case: true

springdoc:
  swagger-ui:
    display-request-duration: true  # API 요청 지속 시간 표시 (m/s)
    defaultModelsExpandDepth: -1  # Schema 표시 여부 (기본값: 1 (표시))

pagehelper:
  autoDialect: true # DB 자동 감지
  closeConn: true # 페이지 처리 완료 시 Connection 자동 닫힘
#  orderBySqlParser: com.example.demo.MyOrderBySqlParser # ORDER BY 절에 대한 사용자 정의 파서
#  offset-as-page-num: true # OFFSET을 페이지 번호로 사용
#  count-column: * # COUNT 함수에서 사용할 열 지정
#  async-count: true # COUNT 쿼리 비동기 처리